// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-purchase-orders.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_purchase_orders_default = defineTool({
  name: "list_purchase_orders",
  title: "List purchase orders",
  description: "List purchase orders (POs) for the signed-in supplier. Returns PO number, date, status, amount, and expected delivery date.",
  inputSchema: {
    status: z.string().optional().describe("Optional status filter, e.g. 'pending', 'open', 'closed'."),
    limit: z.number().int().min(1).max(200).optional().default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    let q = sb.from("purchase_orders").select("po_number, date, status, amount, expected_delivery").order("date", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { count: data?.length ?? 0, purchase_orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-invoices.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_invoices_default = defineTool2({
  name: "list_invoices",
  title: "List invoices",
  description: "List invoices submitted by the signed-in supplier, including status, amount, balance and due date.",
  inputSchema: {
    status: z2.string().optional().describe("Optional status filter, e.g. 'pending', 'paid', 'open'."),
    limit: z2.number().int().min(1).max(200).optional().default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser2(ctx);
    let q = sb.from("invoices").select("invoice_number, date, status, amount, balance, due_date, payment_date, po_id").order("date", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { count: data?.length ?? 0, invoices: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-payments.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_payments_default = defineTool3({
  name: "list_payments",
  title: "List payments",
  description: "List payments the signed-in supplier has received against their invoices, with amount, mode, date, and reference.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).optional().default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser3(ctx);
    const { data, error } = await sb.from("payments").select("payment_number, date, amount, status, payment_mode, transaction_id, invoice_id").order("date", { ascending: false }).limit(limit ?? 50);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { count: data?.length ?? 0, payments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-supplier-profile.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_supplier_profile_default = defineTool4({
  name: "get_supplier_profile",
  title: "Get supplier profile",
  description: "Return the signed-in supplier's profile: contact name, company, email, phone, GST number, and address.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser4(ctx);
    const { data, error } = await sb.from("suppliers").select("name, company, email, phone, gst_number, address").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "agrhkarauqxkgyvfthvc";
var mcp_default = defineMcp({
  name: "emboss-supplier-portal",
  title: "Emboss Supplier Portal",
  version: "0.1.0",
  instructions: "Tools for the Emboss Marketing supplier portal. Use these to look up the signed-in supplier's purchase orders, invoices, payments, and account profile. All data is scoped to the authenticated supplier.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_purchase_orders_default, list_invoices_default, list_payments_default, get_supplier_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
